# Generated by Django 4.1.3 on 2022-12-21 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ppsproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Какое-то описание продукта', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('P', 'Processing'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='./static/prods'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='photo',
            field=models.ImageField(upload_to='./static/logos'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='state',
            field=models.CharField(choices=[('P', 'Processing'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
