# Generated by Django 4.1.3 on 2022-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsproj', '0002_product_description_alter_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./static/prods'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./static/logos'),
        ),
    ]
