# Generated by Django 4.1.3 on 2022-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsproj', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='state',
            field=models.CharField(default='c', max_length=1),
            preserve_default=False,
        ),
    ]
