# Generated by Django 4.1.3 on 2022-12-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsproj', '0003_alter_product_photo_alter_provider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='state',
            field=models.CharField(choices=[('A', 'Processing'), ('B', 'WaitingPayment'), ('C', 'WaitingDeliver'), ('D', 'Delivered'), ('E', 'Rejected')], default='A', max_length=1),
        ),
    ]
