# Generated by Django 4.1.3 on 2022-12-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsproj', '0004_alter_shoppingcart_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='state',
            field=models.CharField(choices=[('A', 'Processing'), ('B', 'WaitingPayment'), ('C', 'Confirmed'), ('D', 'Rejected')], default='A', max_length=1),
        ),
    ]
